.create external table extStormEvents (
    StartTime: datetime,
    EndTime: datetime,
    EpisodeId: int,
    EventId: int,
    State: string,
    EventType: string,
    InjuriesDirect: int,
    InjuriesIndirect: int,
    DeathsDirect: int,
    DeathsIndirect: int,
    DamageProperty: int,
    DamageCrops: int,
    Source: string,
    BeginLocation: string,
    EndLocation: string,
    BeginLat: real,
    BeginLon: real,
    EndLat: real,
    EndLon: real,
    EpisodeNarrative: string,
    EventNarrative: string,
    StormSummary: dynamic
) 
kind = blob 
partition by (StartTime:datetime = startofday(StartTime))
pathformat = ("StartTime=" datetime_pattern("yyyy-MM-dd", StartTime))
dataformat = parquet 
(
    h@'https://mystorageaccount.blob.core.windows.net/storm-events/;******' 
) 
with ( 
    compressed = true,
    folder = 'External',
    docstring = 'archive copy of StormEvents'
)
